---
title: "Academics"
---

Here is an overview of my academic career and teaching activities. For more details on these, please take a look at my [CV](https://www.public-health.uiowa.edu/wp-content/uploads/2022/07/CV-Roberts.pdf).

## Education

- **PhD Biostatistics**, University of Michigan, 2016 - 2022

Dissertation “Causal Inference Methods and Intermediate Endpoints in Randomized Clinical Trials”

Advisors: Drs. Jeremy Taylor and Michael Elliott

- **MS Biostatistics**, University of Michigan, 2018

- **Bachelor of Arts, Mathematics and Psychology**, Coe College, Cedar Rapids, Iowa, 2016

Summa Cum Laude 

GPA 3.99, Mathematics Departmental Distinction, Scholar’s Program, 
Honors thesis “Roommate Matching by Design” Advisor: Dr. Jonathan White


## Research Experience: Graduate

University of Michigan, Ann Arbor, Michigan	

National Institutes of Health Cancer Training in Biostatistics Grant Trainee, Sept 2016-Aug 2017

Advisor: Dr. Jeremy Taylor

Graduate Student Research Assistant Advisor: Dr. Philip Boonstra, May-Aug 2019

Advisor: Dr. Lili Zhao, 2019, Sept 2020-2022

Advisor: Dr. Matt Schipper, June 2020-2022

Co-PI Telomere Research Network Pilot Project Grant under Dr. Belinda Needham, Aug 2020-2022

Research Experience: Undergraduate

Harvard Summer Program in Biostatistics and Computational Biology Boston, Massachusetts, June-July 2015

Action Research: Mission of Hope Cedar Rapids, Iowa, Jan-May 2015

Columbia Summer Institute in Biostatistics New York City, New York, May-July 2014

Coe College Research in Mathematics Program Cedar Rapids, Iowa, June-Aug 2013

## Awards and Distinctions


Phi Beta Kappa, Mortar Board, Psi Chi, Alpha Lambda Delta, Phi Kappa Phi

Dean’s List Coe College 2012-2016

Coe College Hunt Award in Mathematics 2015
	
Barry Goldwater Honorable Mention 2015

R.J. McElroy Fellowship 2016

University of Michigan School of Public Health Regents’ Fellowship Award	2016

National Science Foundation Graduate Research Fellowship Program 2016-2021

School of Public Health Unsung Hero Award 2020

University of Michigan Rackham Predoctoral Fellowship 2021-2022

University of Michigan Department of Biostatistics Excellence in Research Honorable Mention 2021

Rackham Graduate Travel Grant 2018, 2019, 2021, 2022

Michigan Institute of Data Science Travel Grant 2019

SAMSI Travel Grant 2019

Telomere Network Analysis Award and Travel Grant 2020, 2021

Michigan Institute of Data Science Symposium November 2019: "Most Likely to Make an Impact in the Field" Award for Incorporating Subgroups in a Surrogate Endpoint Setting

Michigan Student Symposium for Interdisciplinary Statistical Sciences (MSSISS) Annual Symposium February 2020: "Best Speed Oral Presentation" Presentation/Poster Award for Incorporating Subgroups in a Surrogate Endpoint Setting

Michigan Student Symposium for Interdisciplinary Statistics Symposium February 2021: "Best Speed Oral Presentation" Presentation/Poster Award for Validating Surrogate Endpoints with Longitudinal Outcomes

Society for Clinical Trials May 2022, Best Poster Award for Evaluating Intermediate Clinical Endpoints for Futility Analysis in Clinical Trials

Women in Statistics and Data Science 2022 Travel Grant

American Statistical Association Lifetime Data Science 2023 Paper Award

Junior Faculty Opportunity Award, University of Iowa 2023

New Faculty Research Award, University of Iowa 2023


## Grants and Awarded Funding 

National Institute of Neurological Disorders and Stroke (NINDS) NeuroNEXT. U01 NS077352-11. Coffey, C. PI. 09/2022-Present. Role: Co-Investigator.

University of Iowa Center for Public Health Statistics. Oleson, J. PI. 10/2022-Present. Role: Co-Investigator.

Completed

NIH U24 AG066528-01: Telomere Research Network, Telomere Research Network Analysis Award, 2020-2021, $4,000, (PI: Stacy Drury). Role: Co-PI on project exploring mediation of the Black/White telomere length difference by persistent organic pollutant exposure.

WSDS Travel Grant 2022, Rackham Graduate Travel Grant 2018, 2019, 2021, 2022, Michigan Institute of Data Science Travel Grant 2019, SAMSI Travel Grant 2019, Telomere Network Analysis Award and Travel Grant 2020, 2021

JSM 2023 Paper and Travel Award, LiDS Section

## Society Membership

American Statistical Association, ENAR, Society for Clinical Trials, Caucus for Women in Statistics


