---
title: "More about me"
---

Outside of research, I enjoy traveling, photography, salsa dancing, baking, and podcasts. I love cheering for my favorite teams - go blue and go Hawks (especially Iowa women's basketball)! I am also passionate about combining my academic interests with public good, and am currently or have been involved in outreach efforts such as [Girls Who Code](http://umich.edu/~girlswc/), [Statistics in the Community (Statcom)](https://sph.umich.edu/biostat/statcom/), and the [Iowa chapter of the American Statistical Association](https://community.amstat.org/iowachapter/home).

### Beyond Type One

I trained for my first marathon! I was a part of the 2022 Beyond Type Run charity team to raise awareness and increase resources for type one diabetics. You can [read more about my story and help support here.](https://donate.beyondtype1.org/fundraiser/4021305) Diabetes has played a major role in my life, including in my academic pursuits toward being involved in meaningful and impactful medical research. I'm always happy to share more about my journey if you're interested in learning more about T1D.


### Links and Fun News

```{r, echo = F}
library(tweetrmd)
tweet_embed("https://x.com/emilyk_roberts/status/1783139025718595946", hide_media = F)
tweet_embed("https://x.com/emilyk_roberts/status/1779860588098662845", hide_media = F)
tweet_embed("https://twitter.com/ENAR_ibs/status/1767347114219045012", hide_media = F)
tweet_embed("https://twitter.com/emilyk_roberts/status/1767163643282555013", hide_media = F)
tweet_embed("https://twitter.com/emilyk_roberts/status/1766816274037014821", hide_media = F)
tweet_embed("https://twitter.com/emilyk_roberts/status/1748068958442299436", hide_media = F)

tweet_embed("https://twitter.com/emilyk_roberts/status/1728927190082081056", hide_media = F)
tweet_embed("https://twitter.com/UIowaCPH/status/1709927767226384664", plain = T, hide_media = F)
tweet_embed("https://twitter.com/emilyk_roberts/status/1708832495716663531", hide_media = F)
tweet_embed("https://twitter.com/emilyk_roberts/status/1707018821091864909", hide_media = F)
tweet_embed("https://twitter.com/emilyk_roberts/status/1715422500366987296", hide_media = F)
tweet_embed("https://twitter.com/emilyk_roberts/status/1689240368938655744", hide_media = F)
tweet_embed("https://twitter.com/proffcoff/status/1684899612228792320", hide_media = F)
tweet_embed("https://twitter.com/emilyk_roberts/status/1671165496396484608", hide_media = F)
tweet_embed("https://twitter.com/emilyk_roberts/status/1658878065898815510", hide_media = F)
tweet_embed("https://twitter.com/proffcoff/status/1645975286402392065", hide_media = F)
tweet_embed("https://twitter.com/emilyk_roberts/status/1637859594650124288", hide_media = F)
```
